### ISSUE TITLE
`pip install aiovalidator` fails

### ISSUE THREAD

**Issue by pomidoroshev** [vir-mir/aiovalidator#24]
Dockerfile:

```Dockerfile
FROM python:3.5

RUN pip install -U pip

RUN pip install aiovalidator
```

Shell:
```
$ docker build -t aiovalidator .
...
Step 3 : RUN pip install aiovalidator
 ---> Running in 9a1b0772cd97
Collecting aiovalidator
  Downloading aiovalidator-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xnbk7er9/aiovalidator/setup.py", line 59, in <module>
        long_description='\n\n'.join((read('README.rst'), read('CHANGES.txt'))),
      File "/tmp/pip-build-xnbk7er9/aiovalidator/setup.py", line 17, in read
        return open(os.path.join(os.path.dirname(__file__), f)).read().strip()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-xnbk7er9/aiovalidator/CHANGES.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xnbk7er9/aiovalidator/
The command '/bin/sh -c pip install aiovalidator' returned a non-zero code: 1
```

**Comment by vir-mir** [comment]
@pomidoroshev Corrected.
